apiVersion: v1
kind: Namespace
metadata:
  name: chaos-test
  labels:
    name: chaos-test
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: chaos-test
  labels:
    app: nginx
spec:
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: chaos-test
  annotations:
    chaosblade.io/chaos: "true"
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 0.2
              memory: 100Mi